name: pick_delivery
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  uuid: ^2.2.2
  path_provider: ^1.6.14
  flutter_image_compress: ^0.7.0
  image_picker: ^0.6.7+7
  cached_network_image: ^2.0.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  firebase_database: ^4.1.0
  flutter_paystack: ^1.0.3
  flutter_launcher_icons: ^0.8.0
  email_validator: ^1.0.5
  google_fonts:  0.2.0
  dots_indicator: ^0.0.4
  flutter_statusbarcolor: 0.2.3
  flutter_rating_bar: 3.0.1+1
  simple_animations: 1.3.8
  percent_indicator: ^2.1.1
  snaplist:
  flutter_svg: ^0.17.4
  flutter_slidable:
  flutter_staggered_grid_view:
  auto_size_text:
  flutter_staggered_animations:
  nb_utils: 3.0.3
  flutter_multi_carousel: ^1.0.0
  intl:
  dashed_circle: 0.0.1
  url_launcher: ^5.0.3
  fluttertoast: ^3.1.3
  http:
  shared_preferences:
  connectivity:
  firebase_core:
  firebase_analytics:
  provider:
  google_sign_in:
  geocoder:
  html:
  google_maps_flutter: ^0.5.32
  geolocator: ^6.0.0+4
  location: ^3.0.2
  google_maps_webservice: ^0.0.18
  flutter_google_places: ^0.2.6
  geoflutterfire: ^2.2.1
  rxdart: ^0.24.1
  firebase_messaging: ^7.0.3
  after_layout:
  liquid_pull_to_refresh:
  expandable:
  flutter_custom_clippers:
  livestream:
  sliding_up_panel:
  wave:
  signature:
  folding_cell:
  flutter_fluid_slider:
  liquid_swipe:
  lipsum:
  flutter_colorpicker:
  rating_bar:
  call_number: 0.0.1
  clippy_flutter: 1.1.1
  flutter_tags: ^0.4.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/theme1/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/theme1/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

